# Generated by Django 4.2.7 on 2025-11-23 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(help_text='Event type: created, started, completed, failed, etc.', max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('worker_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'job_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['job_id', 'timestamp'], name='job_history_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_job_id', models.UUIDField(db_index=True)),
                ('job_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('retry_count', models.IntegerField()),
                ('final_error_message', models.TextField()),
                ('final_error_trace', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('retried', models.BooleanField(default=False)),
                ('retried_at', models.DateTimeField(blank=True, null=True)),
                ('new_job_id', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'dead_letter_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(db_index=True, help_text="Type of job to process (e.g., 'send_email', 'process_data')", max_length=100)),
                ('payload', models.JSONField(help_text='Job data/parameters as JSON')),
                ('result', models.JSONField(blank=True, help_text='Job result data after completion', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], db_index=True, default='pending', max_length=20)),
                ('version', models.IntegerField(default=0, help_text='Version number for optimistic locking')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('lease_until', models.DateTimeField(blank=True, db_index=True, help_text='Lease expiry time - job can be re-assigned after this', null=True)),
                ('worker_id', models.CharField(blank=True, help_text='ID of worker currently processing this job', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Unique key to prevent duplicate job submissions', max_length=255, null=True, unique=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Higher priority jobs processed first')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last heartbeat from worker', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='job_queue_idx'), models.Index(fields=['status', 'lease_until'], name='job_lease_idx'), models.Index(fields=['tenant', 'status', 'created_at'], name='job_tenant_idx'), models.Index(fields=['job_type', 'status'], name='job_type_status_idx')],
            },
        ),
    ]
