# Generated by Django 4.2.7 on 2025-11-23 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tenant/organization name', max_length=255)),
                ('api_key', models.CharField(db_index=True, help_text='API key for authentication', max_length=64, unique=True)),
                ('max_concurrent_jobs', models.IntegerField(default=5, help_text='Maximum number of jobs that can run simultaneously')),
                ('max_jobs_per_minute', models.IntegerField(default=10, help_text='Rate limit: max jobs per minute')),
                ('max_jobs_per_hour', models.IntegerField(default=100, help_text='Rate limit: max jobs per hour')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_type', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], max_length=10)),
                ('request_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'rate_limit_tracker',
                'indexes': [models.Index(fields=['tenant', 'window_start', 'window_type'], name='rate_limit__tenant__dd306b_idx')],
                'unique_together': {('tenant', 'window_start', 'window_type')},
            },
        ),
    ]
